name: Development CI/CD

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

permissions:
  id-token: write
  contents: read
  pages: write  

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint HTML
        run: npx htmlhint src/**/*.html
      - name: Lint CSS
        run: npx stylelint styles/**/*.css

  build:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build website
        run: npx parcel build src/index.html --dist-dir dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: development-env
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4