name: Staging CD

on:
  push:
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build website
        run: npx parcel build src/index.html --out-dir dist
      - name: Deploy to Staging
        uses: actions/deploy-pages@v4